# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-06-05 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='activo',
            field=models.CharField(blank=True, default='SI', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_baja',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de baja'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='motivo',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='tipo_baja',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='conyugue',
            name='apellido_materno',
            field=models.CharField(max_length=60, verbose_name='Apellido materno del conyugue'),
        ),
        migrations.AlterField(
            model_name='conyugue',
            name='apellido_paterno',
            field=models.CharField(max_length=60, verbose_name='Apellido paterno del conyugue'),
        ),
        migrations.AlterField(
            model_name='conyugue',
            name='email',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='conyugue',
            name='email_trabajo',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='conyugue',
            name='lugar_de_trabajo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='conyugue',
            name='nombre',
            field=models.CharField(max_length=60, verbose_name='Nombre del conyugue'),
        ),
        migrations.AlterField(
            model_name='conyugue',
            name='profesion',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='conyugue',
            name='tlf',
            field=models.CharField(max_length=15, verbose_name='Tel'),
        ),
        migrations.AlterField(
            model_name='licenciasconducir',
            name='fecha_vigencia',
            field=models.DateTimeField(verbose_name='Fecha de termino de vigencia'),
        ),
    ]
