# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-06-09 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_auto_20190605_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='motivo',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Motivo'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='tipo_baja',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Tipo de baja'),
        ),
    ]
