# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-05-02 08:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
        ('candidatos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='curp',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='CURP'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='pais_direc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pais_de_direccion_cand', to='empleados.Country'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='pais_nacimiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pais_nacimiento_cand', to='empleados.Country'),
        ),
        migrations.AlterField(
            model_name='referencia',
            name='referencia_annios_conocer',
            field=models.CharField(max_length=2, verbose_name='Años de conocerlo'),
        ),
    ]
