# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-05-02 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0002_auto_20190502_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='edad',
            field=models.CharField(max_length=3, verbose_name='Edad'),
        ),
    ]
