# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-05-02 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0005_auto_20190502_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='fuente_recluta',
            field=models.CharField(max_length=100, null=True, verbose_name='Fuente de reclutamiento'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='puesto_solicitado',
            field=models.CharField(max_length=100, null=True, verbose_name='Puesto solicitado'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='sueldo_deseado',
            field=models.CharField(max_length=6, null=True, verbose_name='Sueldo deseado'),
        ),
    ]
