# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-05-02 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0006_auto_20190502_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='sexo',
            field=models.CharField(max_length=9, verbose_name='Sexo'),
        ),
    ]
