# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-05-02 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0007_auto_20190502_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='especialidad',
            field=models.CharField(max_length=100, null=True, verbose_name='Especialidad'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='postgrado',
            field=models.CharField(max_length=100, null=True, verbose_name='Postgrado'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='tecnica',
            field=models.CharField(max_length=100, null=True, verbose_name='Técnica'),
        ),
    ]
