# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-05-03 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0008_auto_20190502_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='padre_tel',
            field=models.CharField(max_length=10, null=True, verbose_name='Teléfono o celular del padre'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='fecha_disponible',
            field=models.DateTimeField(verbose_name='Fecha disponible para iniciar'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='tel',
            field=models.CharField(max_length=10, null=True, verbose_name='Teléfono'),
        ),
    ]
