# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-05-03 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0009_auto_20190503_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='fecha_disponible',
            field=models.DateTimeField(null=True, verbose_name='Fecha disponible para iniciar'),
        ),
    ]
