# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-05-03 17:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0012_auto_20190503_0025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidato',
            name='especialidad_domicilio',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='postgrado_domicilio',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='preparatoria_domicilio',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='primaria_domicilio',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='profesional_domicilio',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='secundaria_domicilio',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='tecnica_domicilio',
        ),
    ]
