# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-05-03 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0013_auto_20190503_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='trayectoria_de_casa',
            field=models.CharField(max_length=60, null=True, verbose_name='Tiempo de trayectoria desde casa'),
        ),
    ]
