# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-05-04 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0014_auto_20190503_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='licencia',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de licencia'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='tipo_licencia',
            field=models.CharField(max_length=20, verbose_name='Tipo de licencia'),
        ),
    ]
