# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-05-04 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0015_auto_20190504_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='cartilla',
            field=models.IntegerField(blank=True, max_length=10, null=True, verbose_name='Número de Cartilla'),
        ),
    ]
