# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-05-04 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0016_auto_20190504_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='licencia',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Número de licencia'),
        ),
    ]
