# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-05-05 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0017_auto_20190504_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='cartilla',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de Cartilla'),
        ),
        migrations.AlterField(
            model_name='hijo_candidato',
            name='hijo_domicilio',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Domicilio del hijo'),
        ),
        migrations.AlterField(
            model_name='hijo_candidato',
            name='hijo_edad',
            field=models.IntegerField(blank=True, null=True, verbose_name='Edad del hijo'),
        ),
        migrations.AlterField(
            model_name='hijo_candidato',
            name='hijo_lugar_ocupacion',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Lugar de trabajo del hijo'),
        ),
        migrations.AlterField(
            model_name='hijo_candidato',
            name='hijo_ocupacion',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Ocupación del hijo'),
        ),
        migrations.AlterField(
            model_name='hijo_candidato',
            name='hijo_tel',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Teléfono o celular del hijo'),
        ),
    ]
