# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-05-05 13:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0018_auto_20190505_1350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hermano_candidato',
            old_name='hermano',
            new_name='candidato',
        ),
        migrations.RenameField(
            model_name='hijo_candidato',
            old_name='hijo',
            new_name='candidato',
        ),
    ]
