# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-05-05 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0019_auto_20190505_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hermano_candidato',
            name='hermano_domicilio',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Domicilio del hermano'),
        ),
        migrations.AlterField(
            model_name='hermano_candidato',
            name='hermano_edad',
            field=models.IntegerField(blank=True, null=True, verbose_name='Edad del hermano'),
        ),
        migrations.AlterField(
            model_name='hermano_candidato',
            name='hermano_lugar_ocupacion',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Lugar de trabajo del hermano'),
        ),
        migrations.AlterField(
            model_name='hermano_candidato',
            name='hermano_ocupacion',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Ocupación del hermano'),
        ),
        migrations.AlterField(
            model_name='hermano_candidato',
            name='hermano_tel',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Teléfono o celular del hermano'),
        ),
    ]
