# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-05-05 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0022_auto_20190505_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencia',
            name='referencia_tel',
            field=models.CharField(max_length=16, verbose_name='Teléfono'),
        ),
    ]
