# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-05-09 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0023_auto_20190505_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='num_ext',
            field=models.CharField(max_length=7, null=True, verbose_name='Número exterior'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='num_int',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Número interior'),
        ),
    ]
