# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-05-14 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0025_auto_20190514_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hermano_candidato',
            name='hermano_edad',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Edad del hermano'),
        ),
    ]
