# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-05-14 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0026_auto_20190514_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='forma',
            field=models.CharField(max_length=50, null=True, verbose_name='Forma de titulación'),
        ),
    ]
