# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-05-14 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0029_auto_20190514_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='especialidad_inicio',
            field=models.CharField(max_length=4, null=True, verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='especialidad_termino',
            field=models.CharField(max_length=4, null=True, verbose_name='Fecha de término'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='postgrado_inicio',
            field=models.CharField(max_length=4, null=True, verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='postgrado_termino',
            field=models.CharField(max_length=4, null=True, verbose_name='Fecha de término'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='preparatoria_inicio',
            field=models.CharField(max_length=4, null=True, verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='preparatoria_termino',
            field=models.CharField(max_length=4, null=True, verbose_name='Fecha de término'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='profesional_inicio',
            field=models.CharField(max_length=4, null=True, verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='profesional_termino',
            field=models.CharField(max_length=4, null=True, verbose_name='Fecha de término'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='secundaria_inicio',
            field=models.CharField(max_length=4, null=True, verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='secundaria_termino',
            field=models.CharField(max_length=4, null=True, verbose_name='Fecha de término'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='tecnica_inicio',
            field=models.CharField(max_length=4, null=True, verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='tecnica_termino',
            field=models.CharField(max_length=4, null=True, verbose_name='Fecha de término'),
        ),
    ]
