# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-05-18 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0030_auto_20190514_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='conyuge_vive',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='candidato',
            name='madre_vive',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='candidato',
            name='padre_vive',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name=''),
        ),
    ]
