# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-05-18 18:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0031_auto_20190518_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudios_pro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudios_tipo', models.CharField(max_length=12, verbose_name='Tipo de estudio')),
                ('estudios_escuela', models.CharField(max_length=100, null=True, verbose_name='Lugar')),
                ('estudios_nombre', models.CharField(max_length=50, null=True, verbose_name='Estudio')),
                ('estudios_annios', models.IntegerField(blank=True, null=True, verbose_name='Años cursados')),
                ('estudios_inicio', models.CharField(max_length=4, null=True, verbose_name='Fecha de inicio')),
                ('estudios_termino', models.CharField(max_length=4, null=True, verbose_name='Fecha de término')),
                ('estudios_documento', models.CharField(max_length=50, null=True, verbose_name='Documento recibido')),
                ('estudios_tesis', models.CharField(max_length=50, null=True, verbose_name='Nombre de tesis')),
                ('estudios_forma', models.CharField(max_length=50, null=True, verbose_name='Forma de titulación')),
                ('estudios_cedula', models.IntegerField(blank=True, null=True, verbose_name='Número de cédula')),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudios_candidato', to='candidatos.Candidato')),
            ],
        ),
    ]
