# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-05-18 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0032_estudios_pro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudios_pro',
            name='estudios_annios',
            field=models.IntegerField(blank=True, verbose_name='Años cursados'),
        ),
        migrations.AlterField(
            model_name='estudios_pro',
            name='estudios_documento',
            field=models.CharField(max_length=50, verbose_name='Documento recibido'),
        ),
        migrations.AlterField(
            model_name='estudios_pro',
            name='estudios_escuela',
            field=models.CharField(max_length=100, verbose_name='Lugar'),
        ),
        migrations.AlterField(
            model_name='estudios_pro',
            name='estudios_inicio',
            field=models.CharField(max_length=4, verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='estudios_pro',
            name='estudios_nombre',
            field=models.CharField(max_length=50, verbose_name='Estudio'),
        ),
        migrations.AlterField(
            model_name='estudios_pro',
            name='estudios_termino',
            field=models.CharField(max_length=4, verbose_name='Fecha de término'),
        ),
    ]
