# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-05-19 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0033_auto_20190518_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudios_pro',
            name='estudios_cedula',
            field=models.CharField(max_length=8, null=True, verbose_name='Número de cédula'),
        ),
    ]
