# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-05-19 12:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0034_auto_20190519_1031'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Idioma',
            new_name='Idioma_candidato',
        ),
    ]
