# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-05-22 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0036_candidato_email_personal'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencia',
            name='empresa_actual',
            field=models.CharField(default=2, max_length=2, verbose_name='¿Empresa actual?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidato',
            name='email_personal',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Correo personal'),
        ),
    ]
