# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-05-23 00:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0037_auto_20190522_2332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudios_otros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudios_tipo', models.CharField(max_length=12, verbose_name='Tipo de estudio')),
                ('estudios_nombre', models.CharField(max_length=50, verbose_name='Estudio')),
                ('estudios_inicio', models.CharField(max_length=4, verbose_name='Fecha de inicio')),
                ('estudios_termino', models.CharField(max_length=4, verbose_name='Fecha de término')),
                ('estudios_documento', models.CharField(max_length=50, verbose_name='Documento recibido')),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiosotros_candidato', to='candidatos.Candidato')),
            ],
        ),
    ]
