# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-05-29 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0040_auto_20190529_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='madre_edad',
            field=models.IntegerField(blank=True, null=True, verbose_name='Edad de la madre'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='padre_edad',
            field=models.IntegerField(blank=True, null=True, verbose_name='Edad del padre'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='tesis',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre de tesis'),
        ),
    ]
