# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-05-29 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0041_auto_20190529_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='conyuge_edad',
            field=models.IntegerField(blank=True, null=True, verbose_name='Edad del conyuge'),
        ),
    ]
