# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-05-29 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0042_auto_20190529_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='emp_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID de empleado'),
        ),
    ]
