# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-06-02 11:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0043_candidato_emp_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cand_docs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('INE', models.BooleanField(default=False, verbose_name='INE')),
                ('Acta', models.BooleanField(default=False, verbose_name='Acta de nacimiento')),
                ('CURP', models.BooleanField(default=False, verbose_name='CURP')),
                ('RFC', models.BooleanField(default=False, verbose_name='RFC')),
                ('Comp_dom', models.BooleanField(default=False, verbose_name='Comprobante de domicilio')),
                ('Comp_grado', models.BooleanField(default=False, verbose_name='Comprobante de último grado')),
                ('Comp_cursos', models.BooleanField(default=False, verbose_name='Comprobantes de cursos, certificaciones, etc.')),
                ('Comp_permiso', models.BooleanField(default=False, verbose_name='Comprobante de permiso laboral(solo extranjero)')),
                ('IMSS', models.BooleanField(default=False, verbose_name='Afiliación al IMSS')),
                ('Cartas', models.BooleanField(default=False, verbose_name='Cartas de recomendación')),
                ('Esdo_cuenta', models.BooleanField(default=False, verbose_name='Esdo. cuenta bancario, tarjeta y CLABE')),
                ('Esdo_info', models.BooleanField(default=False, verbose_name='Esdo. cuenta Infonacot/infonavit')),
                ('Lic_manejo', models.BooleanField(default=False, verbose_name='Lic. de manejo')),
                ('Observaciones', models.TextField(max_length=200, null=True, verbose_name='Observaciones')),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docs_candidato', to='candidatos.Candidato')),
            ],
        ),
    ]
