# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-06-06 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0046_auto_20190606_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='esdo',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Estado'),
        ),
    ]
