# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-06-06 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0048_auto_20190606_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencia',
            name='empresa_direccion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='empresa_puesto_anterior',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Anterior puesto desempeñado'),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='empresa_puesto_anterior_depto',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Departamento del anterior puesto desempeñado'),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='empresa_puesto_anterior_tiempo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tiempo del anterior puesto'),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='empresa_tel',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='experiencia_supervision_num',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Número de personas que superviso'),
        ),
    ]
