# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-06-06 19:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0049_auto_20190606_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumentoIdentidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='carrera',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='cedula',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='especialidad',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='especialidad_annios',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='especialidad_documento',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='especialidad_inicio',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='especialidad_nombre',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='especialidad_termino',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='forma',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='postgrado',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='postgrado_annios',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='postgrado_documento',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='postgrado_inicio',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='postgrado_nombre',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='postgrado_termino',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='profesional',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='profesional_annios',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='profesional_documento',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='profesional_inicio',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='profesional_termino',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='tesis',
        ),
        migrations.AddField(
            model_name='candidato',
            name='docu_ident_back',
            field=models.ImageField(blank=True, null=True, upload_to='documentos_identidad/'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='docu_ident_front',
            field=models.ImageField(blank=True, null=True, upload_to='documentos_identidad/'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='imagen_curp',
            field=models.ImageField(blank=True, null=True, upload_to='curps/'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='imagen_imss',
            field=models.ImageField(blank=True, null=True, upload_to='imss/'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='imagen_lic_anverso',
            field=models.ImageField(blank=True, null=True, upload_to='licencias_conducir/'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='imagen_lic_reverso',
            field=models.ImageField(blank=True, null=True, upload_to='licencias_conducir/'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='imagen_rfc',
            field=models.ImageField(blank=True, null=True, upload_to='rfcs/'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='tipo_documento_identidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_docu_ident', to='candidatos.TipoDocumentoIdentidad'),
        ),
    ]
