# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-06-06 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0050_auto_20190606_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='imagen_cartilla',
            field=models.ImageField(blank=True, null=True, upload_to='documentos_identidad/'),
        ),
    ]
