# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-06-06 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0051_candidato_imagen_cartilla'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='activo',
            field=models.CharField(blank=True, default='SI', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='fecha_baja',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de baja'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='motivo',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Motivo'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='tipo_baja',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Tipo de baja'),
        ),
    ]
