# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-06-10 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0054_candidato_imagen_infonavit'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='acta_nacimiento',
            field=models.ImageField(blank=True, null=True, upload_to='actas_nacimiento/'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='carta1_recomendacion',
            field=models.FileField(blank=True, null=True, upload_to='cartas_recomendacion/'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='carta2_recomendacion',
            field=models.FileField(blank=True, null=True, upload_to='cartas_recomendacion/'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='comprobante_domicilio',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes_domicilio/'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='contrato',
            field=models.FileField(blank=True, null=True, upload_to='bancos/'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='curriculum',
            field=models.FileField(blank=True, null=True, upload_to='curriculums/'),
        ),
    ]
