# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-06-10 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0055_auto_20190610_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='INE_atrasTut',
            field=models.ImageField(blank=True, null=True, upload_to='documentos_identidad/'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='INE_frenteTut',
            field=models.ImageField(blank=True, null=True, upload_to='documentos_identidad/'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='carta_menor',
            field=models.ImageField(blank=True, null=True, upload_to='cartas_menor/'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='oficio',
            field=models.ImageField(blank=True, null=True, upload_to='oficios/'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='permiso',
            field=models.ImageField(blank=True, null=True, upload_to='permisos/'),
        ),
    ]
