# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-06-14 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0057_auto_20190613_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudios_otros',
            name='comprobante',
            field=models.FileField(blank=True, null=True, upload_to='compro_est_otros/'),
        ),
        migrations.AlterField(
            model_name='estudios_pro',
            name='comprobante',
            field=models.FileField(blank=True, null=True, upload_to='compro_est_pro/'),
        ),
    ]
